type Actor = 'user' | 'host' | 'runtime' | 'jev' | 'worker';
type NodeData = { id: string; lane: number; row: number; actor: Actor; title: string; sub: string; skill: string; input: string; actions: string[]; output: string; kind?: 'start' | 'end' };
type Edge = { from: string; to: string; label?: string; type?: 'return' | 'fallback' };
type View = { title: string; description: string; lanes: [string,string,Actor][]; nodes: NodeData[]; edges: Edge[]; initial: string };
const n = (id:string,lane:number,row:number,actor:Actor,title:string,sub:string,skill:string,input:string,actions:string[],output:string,kind?:'start'|'end'):NodeData => ({id,lane,row,actor,title,sub,skill,input,actions,output,kind});
const e = (from:string,to:string,label='',type?:'return'|'fallback'):Edge => ({from,to,label,type});
const hostName = () => (document.getElementById('host') as HTMLSelectElement).value === 'fable' ? 'Claude / Fable' : 'Codex / Astra';
const views:Record<string,View> = {
flow:{title:'The complete execution path',description:'Start at the user. Follow the host into Jev decisions, concurrent specialist work, and evidence-backed returns. Click nodes to trace connected paths.',lanes:[['You','Intent & real permissions','user'],['{host}','Coordinator / session owner','host'],['TypeScript runtime','Scheduling, tools & state','runtime'],['Jev','Bounded semantic decisions','jev'],['Specialist subagents','pi / OpenRouter workers','worker']],initial:'start',nodes:[
n('start',0,0,'user','START · /amaleh <task>','Invoke once, or resume an existing run','amaleh / entry (planned)','Your requested outcome and existing authorization',['Load the canonical Amaleh skill in the invoking session.','Resume existing work when a matching run exists; do not recreate completed tasks.'],'Intent and caller context delivered to {host}.','start'),
n('intake',1,0,'host','Own the outcome','{host} remains the coordinator','amaleh / intake (planned)','User request, repository facts, current model identity',['Inspect relevant code and state.','Capture concrete acceptance criteria and exclude hypothetical scope.','Ask only for missing user intent that cannot be discovered.'],'A compact intent contract and evidence needs.'),
n('discover',2,0,'runtime','Discover capabilities','Models, tools, permissions, live state','amaleh / adapters + state (planned)','Host context, configured model pools, repository state',['Resolve actual model identity and available execution channels.','Check worker tools/modalities and reconcile live ownership.','Use cached current catalog facts; preserve pi global defaults.'],'Verified capabilities and resumable run state.'),
n('scope',3,1,'jev','J1 · Choose the route','Small task, research, or parallel work','amaleh / decisions.scope (planned)','Intent, inspected code, evidence gaps, eligible routes',['Judge whether more evidence is needed.','Choose a justified scope and an appropriate work route.','Evaluate atomic questions together when they use the same state.'],'Typed route and uncertainty; no code generation.'),
n('plan',1,1,'host','Shape a small work graph','Options and contracts, not eight phases','amaleh / plan (planned); codebase-design only if architecture needs it','Intent plus Jev route, or uncertainty requiring host judgment',['Propose cohesive tasks and interfaces.','Group coupled files. Identify independent work.','Resolve uncertain Jev judgments and record the fallback.'],'Task graph, acceptance checks, and evidence-backed options.'),
n('schedule',2,2,'runtime','Validate & schedule','Ready dependencies, actual resource capacity','amaleh / graph + scheduler (planned)','Versioned task graph and resource ownership',['Reject duplicate IDs, cycles, missing dependencies, and invalid transitions.','Dispatch ready work without a global wave barrier.','Serialize conflicting resources; checkpoint task ownership.'],'An eligible task with a destination context packet.'),
n('route',3,2,'jev','J2 · Route every task','Research, compact plan, or execute','amaleh / decisions.task (planned)','Task evidence, missing facts, eligible actions, Flash model cards',['For this task, choose source inspection, web research, scratch experiment, compact planning, or execution.','Choose GLM/DeepSeek Flash for routine work; Kimi K3 only for justified depth. See Every task for the full loop.','Use host fallback for uncertainty rather than inventing model strengths.'],'Task-specific route, research targets, and eligible worker configuration.'),
n('dispatch',2,3,'runtime','Prepare & dispatch','Brief + relevant artifacts + allowed tools','amaleh / context + pi adapter (planned)','Selected configuration and dependency artifacts',['Retain constraints, current revision, required checks, and retrieval pointers.','Archive original evidence before filtering context.','Start isolated workers with per-invocation model settings.'],'Tracked worker session or a direct-host task.'),
n('small',1,3,'host','Explicit host exception','User request or exhausted repair','amaleh / host-exception','Scoped host-exception authorization',['Consume a single-use host exception before implementation.','Re-read the own diff against the criteria and reopen reasons before result.','Host work is final: delegate runs the task checks and accepts with no model review.'],'Authorized changes accepted on passing checks.'),
n('coding',4,3,'worker','Implement / investigate','GLM Flash + DeepSeek Flash','amaleh / worker brief (planned); relevant installed skill if selected','Focused task, isolated workspace, tools, and acceptance criteria',['Flash workers do routine source reading, web research, experiments, compact plans, and implementation.','Run task-relevant checks. No nested delegation by default.','Return artifact references, unresolved issues, usage, and next action.'],'Changes + test receipts returned to the runtime and coordinator.'),
n('specialists',4,4,'worker','Design / vision / research','Flash first; Kimi for justified depth','amaleh / specialist brief (planned); frontend-design when relevant','Task-specific role, model, tools, actual images or sources',['Independent research targets can run beside implementation tasks.','Use a capable Flash configuration first; deeper work can route directly to Kimi when the evidence justifies it.','Frontend gets design context; vision gets actual images; research gets retrieval; math gets checked calculations.'],'Specialist artifacts and evidence. Model preference is configurable.'),
n('receipts',2,4,'runtime','Collect verifiable receipts','Diffs, screenshots, source links, check output','amaleh / artifacts + checks (planned)','Host/worker outputs and exact revision identifiers',['Store immutable evidence and structured results.','Run required checks appropriate to the change.','Never promote worker prose to a passed test.'],'Artifacts tied to the actual checked state.'),
n('review',1,5,'host','Inspect results & integrate','Main model reads the evidence','amaleh / review (planned); code-review when warranted','Changes and receipts from all completed tasks',['Inspect actual artifacts, not only worker summaries.','Use targeted independent review when the change warrants it.','Prepare bounded actionable findings and proposed next actions.'],'Evidence-backed findings and integration proposal.'),
n('triage',3,5,'jev','J3 · Triage findings','Relevant defect, repair, replan, or proceed','amaleh / decisions.findings (planned)','Finding, affected behavior, requested scope, supporting evidence',['Separate demonstrated issues from speculative improvements.','Choose repair, upstream diagnosis, or proceed among legal options.','Escalate uncertainty to {host}.'],'Semantic recommendation; failed required checks cannot be overridden.'),
n('integrate',2,6,'runtime','Integrate & unlock work','Required integration checks','amaleh / integration (planned)','Reviewed compatible changes and resource availability',['Serialize the integration boundary where needed.','Invalidate stale verification when relevant content changes.','Unlock dependents immediately after their requirements pass.'],'Updated integrated state; repair or next eligible task.'),
n('accept',1,7,'host','Verify the requested outcome','Main model closes the loop','amaleh / acceptance (planned); verification-before-completion as relevant','Integrated artifact, original intent, all required check receipts',['Confirm each promised outcome against real evidence.','Review visual behavior with actual renderings when required.','Keep incomplete, blocked, and complete states distinct.'],'A completion proposal with exact evidence and remaining limitations.'),
n('completion',3,7,'jev','J4 · Check claim support','Does evidence support each completion claim?','amaleh / decisions.claims (planned)','Individual outcome claim plus relevant source/check evidence',['Judge semantic support and missing qualifications.','Leave exact exit codes and required checks to code.','Uncertainty returns to the host.'],'Supported claims or concrete gaps for repair.'),
n('deliver',0,8,'user','DONE · verified delivery','Result + evidence + honest limitations','amaleh / finish (planned)','Verified outcomes, authorization, archived run evidence',['Receive the completed result and relevant verification evidence.','Publishing or shared-branch changes still require existing authorization.'],'Durable archived run; no false success for exhausted work.','end'),
],edges:[e('start','intake','invoke'),e('intake','discover','inspect'),e('discover','scope','facts'),e('scope','plan','route / uncertainty','return'),e('plan','schedule','task graph'),e('schedule','route','eligible task'),e('route','dispatch','selection','return'),e('route','plan','uncertain → host','fallback'),e('dispatch','small','recorded exception','return'),e('dispatch','coding','dispatch'),e('dispatch','specialists','independent tasks'),e('small','receipts','changes'),e('coding','receipts','worker result','return'),e('specialists','receipts','specialist result','return'),e('receipts','review','evidence','return'),e('review','triage','findings'),e('triage','integrate','proceed'),e('triage','plan','repair / uncertain','fallback'),e('integrate','schedule','dependents ready','fallback'),e('integrate','accept','all work integrated','return'),e('accept','completion','claims'),e('completion','accept','support / gaps','return'),e('accept','plan','real gap → repair','fallback'),e('accept','deliver','verified outcome','return')]},
jev:{title:'Jev is the decision service',description:'The main model proposes and supplies evidence. Jev chooses within a legal shortlist. Code enforces facts and constraints; uncertainty returns to the main model.',lanes:[['{host}','Reason, propose, decide fallback','host'],['Runtime / evidence','Hard filters & calculations','runtime'],['Jev','Typed judgments only','jev'],['Executor','Host or selected worker','worker']],initial:'jtask',nodes:[
n('jtask',0,0,'host','A decision is needed','Scope, model, finding, context, claim','amaleh / decision caller (planned)','Current task and the question that changes the next action',['Frame a bounded choice and collect relevant evidence.','Avoid asking Jev to invent an architecture or solve broad reasoning.'],'Options with task-specific evidence.','start'),
n('jfilter',1,0,'runtime','Construct a legal shortlist','Capabilities & facts first','amaleh / decision preflight (planned)','Configured access, modalities, tools, context, permissions',['Remove incapable or unauthorized candidates.','Compute cost/time estimates without model arithmetic.','Tie the decision to a specific evidence revision.'],'Small eligible option set with sourced cards.'),
n('jcards',1,1,'runtime','Supply model evidence cards','Strengths are supplied, not assumed','amaleh / model registry (planned)','Vendor sources, independent tests, current catalog, local outcomes',['Separate claims from measurements and user preferences.','Record model/provider/effort, source date, and sample counts.','Keep unknown quality unknown.'],'Relevant capabilities, prices, performance, and uncertainty.'),
n('jbatch',2,1,'jev','Evaluate atomic questions','Choice · Score · Noul','amaleh / Jev API adapter (planned)','One relevant state and independent typed questions',['J1: justified scope and work route. J2: task/model/skill fit.','J3: actionable finding versus unsupported scope. J4: claim support.','Context selection: relevance of actual evidence excerpts.'],'Typed answers and probabilities; not prose or runnable commands.'),
n('jvalidate',1,2,'runtime','Validate response & freshness','Schema, ranges, option IDs, revision','amaleh / response validation (planned)','Jev output and the current run revision',['Reject malformed, missing, out-of-range, or stale answers.','Never equate high confidence with permission or test success.','Apply calibrated decision policy; do not invent a universal confidence cutoff.'],'Usable decision or fallback reason.'),
n('jfallback',0,2,'host','Uncertain? Main model decides','Do not stop routine work','amaleh / host fallback (planned)','Uncertain judgment, supplied evidence, available options',['Inspect the evidence and make the decision.','Record that authority temporarily fell back to the invoking model.','Gather essential missing facts when needed.'],'A recorded bounded host decision.'),
n('japply',1,3,'runtime','Apply a valid decision','Code retains execution control','amaleh / transition executor (planned)','Valid Jev or host decision',['Enforce dependencies, resource ownership, and permissions.','Choose a compatible provider for the selected model.','Save decision, source revision, and destination.'],'Authorized execution configuration.'),
n('jexecute',3,3,'worker','Execute with the chosen tools','Model + role + context + verification','amaleh / worker adapter or direct-host route (planned)','Selected task configuration',['Execute the selected work; no automatic model change on every token.','Return actual outputs and tool receipts.'],'Artifacts and measured consumption.'),
n('jlearn',1,4,'runtime','Record the real outcome','Success, time, tokens, repairs','amaleh / run records (planned)','Checked outputs and observed usage',['Update simple task-specific counts.','Use fresh evidence for later routing decisions.','No automatic training platform or paid benchmark sweep.'],'A better evidence card for the next decision.'),
],edges:[e('jtask','jfilter','options'),e('jfilter','jcards','eligible candidates'),e('jcards','jbatch','state + questions'),e('jbatch','jvalidate','typed answers','return'),e('jvalidate','jfallback','uncertain / invalid','fallback'),e('jfallback','japply','host decision'),e('jvalidate','japply','valid decision'),e('japply','jexecute','dispatch'),e('jexecute','jlearn','verified result','return'),e('jlearn','jcards','future evidence','fallback')]},
context:{title:'Context survives the handoff',description:'A smaller working packet is never the only record. Original evidence stays retrievable; main-agent recovery and worker recovery share the same durable state.',lanes:[['{host}','Task owner & resumed context','host'],['Durable runtime','Artifacts, state, live ownership','runtime'],['Jev','Optional relevance selection','jev'],['Workers / adapters','pi, Claude, Codex boundaries','worker']],initial:'csave',nodes:[
n('csave',0,0,'host','Before a handoff or compaction','Capture intent and current work','amaleh / checkpoint (planned)','Current task, accepted decisions, unresolved errors',['Persist the latest user constraints and next action.','Keep irreversible-operation receipts and pending operations.'],'Checkpoint request before context changes.','start'),
n('carchive',1,0,'runtime','Archive original artifacts','Never delete the only evidence','amaleh / artifact store (planned)','Full tool outputs, diffs, image references, test receipts',['Store originals with immutable identifiers and content hashes.','Preserve current graph state and owner identity.','Read-only tool replay is not a universal substitute for archives.'],'Retrievable originals and an atomic checkpoint.'),
n('cpin',1,1,'runtime','Pin essential context','Intent · constraints · decisions · blockers','amaleh / packet builder (planned)','Checkpoint plus destination role',['Keep essential state regardless of Jev relevance.','Load the relevant evidence excerpts, not the entire conversation.','Preserve model-specific tool/reasoning metadata.'],'Pinned header plus optional evidence candidates.'),
n('cselect',2,1,'jev','Select relevant excerpts','Recipient-specific relevance','amaleh / decisions.context (planned)','Actual excerpts and task purpose, not just output lengths',['Choose optional evidence useful to this recipient.','Keep uncertain material or ask the host to inspect it.','Do not authorize deletion of archived originals.'],'Optional context selection with source references.'),
n('cpacket',1,2,'runtime','Build the destination packet','Small brief + retrieval manifest','amaleh / context validator (planned)','Pinned header, selected evidence, provider conversation rules',['Validate paired tool-call/result structure.','Fit the recipient context budget without dropping required facts.','Retain retrieval pointers for omitted evidence.'],'Bounded packet and untouched archive.'),
n('cadapter',3,2,'worker','Apply the supported host hook','Capabilities differ by host','amaleh / lifecycle adapters (planned)','Packet and verified installed host interface',['pi: supported context filtering and custom compaction.','Claude/Codex: checkpoint before, restore context after native compaction.','A skill symlink does not install hooks; no unverified native-summary replacement.'],'Worker context or restored host context.'),
n('cresume',0,3,'host','Resume with focused context','Same outcome, no restart from scratch','amaleh / resume (planned)','Checkpoint, recent messages, pending task and artifact references',['Recover user constraints and accepted decisions.','Inspect missing evidence through archive references.','Continue the next eligible action.'],'Continuation proposal using durable facts.'),
n('creconcile',1,3,'runtime','Reconcile live work','Git + artifacts + active ownership','amaleh / recovery (planned)','Saved status, actual changes, worker identity/liveness',['Do not assume every old in-progress status is dead.','Do not duplicate completed work or steal an active worker.','Re-dispatch unfinished work only after reconciliation.'],'Ready work and trustworthy current status.'),
n('cfailure',3,4,'worker','Credits / persistent API failure','Transient failure → bounded retry','amaleh / provider failure handling (planned)','Provider errors and any surviving partial artifacts',['Preserve progress and release only resources this run owns.','Request top-up or a user-selected alternative when intervention is required.','No artificial total-spend cutoff.'],'Recoverable stop reason, not a false completion.'),
n('cuser',0,4,'host','Explain the needed intervention','Main model reports the exact blocker','amaleh / user handoff (planned)','Failure reason, finished work, retained checkpoint',['Tell the user what failed and what remains.','Resume from checkpoint once the issue is resolved.'],'Resume through the same reconciliation path.'),
],edges:[e('csave','carchive','save originals'),e('carchive','cpin','durable facts'),e('cpin','cselect','optional excerpts'),e('cselect','cpacket','selection','return'),e('cpin','cpacket','pinned always'),e('cpacket','cadapter','context packet'),e('cadapter','cresume','restored context','return'),e('cresume','creconcile','continue request'),e('creconcile','cresume','next valid action','return'),e('cadapter','cfailure','service unavailable','fallback'),e('cfailure','carchive','save partial work','return'),e('cfailure','cuser','needs intervention','return'),e('cuser','creconcile','resume','fallback')]},
skills:{title:'Which skill runs on which model?',description:'Amaleh owns orchestration. External skills are selected tools—not a mandatory Superpowers or BMAD chain. Each worker gets only the instructions and capabilities its task needs.',lanes:[['{host}','One main coordinator','host'],['Amaleh modules','Planned skill + TypeScript core','runtime'],['Jev','Select relevant specialist','jev'],['Role / candidate models','Configurable pools','worker']],initial:'sentry',nodes:[
n('sentry',0,0,'host','/amaleh enters here','Invoking model and effort are inherited','amaleh / SKILL.md (planned)','User request or resume command',['Load one canonical skill through Claude/Codex links.','Keep the invoking model as task owner.','The current grill-me interview designs Amaleh; it is not a required phase for every future task.'],'Orchestration session.','start'),
n('score',1,0,'runtime','Amaleh orchestration modules','Intake → graph → dispatch → verify → finish','amaleh modules (planned, not installed yet)','Intent and repository context',['Provide task-sized prompts and deterministic state/graph tools.','Do not require the full Trellis, Superpowers, or BMAD sequence.','Use Bun first and Node fallback for runtime commands.'],'Explicit execution and evidence contracts.'),
n('sskill',2,1,'jev','Choose only relevant skills','Available catalog + task evidence','amaleh / decisions.skills (planned)','Eligible installed skills, model cards, and task purpose',['Select useful instructions and allow none needed.','Check fit using short descriptions, then relevant full instructions.','Uncertainty returns to the main model.'],'A role configuration with relevant skill references.'),
n('sfront',3,1,'worker','Frontend creation','Capable Flash first; Kimi when deeper','frontend-design (existing optional skill)','Visual direction, reference assets, interaction requirements',['Use the eligible GLM/DeepSeek Flash configuration for routine work.','Use Kimi K3 when task evidence, visual demands, or observed failure justifies deeper work.','Run the app and check both appearance and requested interactions.'],'Frontend code, screenshots, and interaction results.'),
n('svision',3,2,'worker','Visual QA / asset inspection','Image-capable GLM / DeepSeek Flash','amaleh / visual brief (planned); product-design:audit if appropriate','Actual screenshots/images plus expected behavior',['Inspect the actual visual evidence with an image-capable route.','Verify clipping, assets, spacing, focus, and responsive behavior when relevant; Kimi is available for deeper cases.','Image understanding does not mean image generation.'],'Specific visual findings grounded in the supplied artifacts.'),
n('scode',3,3,'worker','General implementation','Latest stable GLM + DeepSeek Flash','amaleh / implementation brief (planned)','Cohesive coding task, existing patterns, relevant tests',['Use the selected model in an isolated worker, including small work.','Resolve latest stable models at run start and record exact IDs; do not change model silently mid-task.','No separate worker for every file and no nested reviewer tree.'],'Code changes and relevant checks.'),
n('sresearch',3,4,'worker','Research / mathematical work','Flash does the footwork','amaleh / research or reasoning brief (planned)','Question, source-access tools, calculation tools, evidence requirements',['Flash workers inspect source, retrieve sources, or run bounded scratch experiments.','Research can fan out across independent targets. Each result returns to the task evidence state.','Use Kimi for justified deeper synthesis and checked computations for math.'],'Cited findings or independently checked reasoning artifacts.'),
n('sarchitecture',0,2,'host','Architecture only when needed','Main model proposes; Jev selects','codebase-design (existing optional skill)','Actual module boundary or interface question',['Inspect the real code and tradeoffs.','Propose bounded options without speculative abstractions.'],'Evidence-backed design options for Jev.'),
n('sreview',0,5,'host','Review & verification','Inspect artifacts; targeted reviewer if justified','code-review + superpowers:verification-before-completion (optional existing skills)','Returned artifacts, acceptance criteria, check receipts',['Use only relevant review instructions.','The verification skill supplies discipline; it is not a separate model.','Main model owns acceptance and cannot claim tests it did not run.'],'Verified outcome or actionable repair request.'),
n('sreturn',1,5,'runtime','Every worker returns here','Structured result → main coordinator','amaleh / result contract (planned)','Artifact IDs, revision, checks, unresolved issues, next action, usage',['Validate result shape and check evidence freshness.','Archive outputs and rehydrate the main model with the relevant packet.','Unlock eligible dependents and account for actual consumption.'],'A concise main-agent handoff backed by retrievable evidence.'),
],edges:[e('sentry','score','load'),e('score','sskill','task + roster'),e('sskill','sfront','frontend route'),e('sskill','svision','visual route'),e('sskill','scode','coding route'),e('sskill','sresearch','research / math'),e('score','sarchitecture','architecture needed','return'),e('sarchitecture','sskill','options'),e('sfront','sreturn','artifacts','return'),e('svision','sreturn','findings','return'),e('scode','sreturn','changes','return'),e('sresearch','sreturn','evidence','return'),e('sreturn','sreview','main receives result','return'),e('sreview','score','actionable repair','fallback')]}
};

views.task={title:'Jev routes each task, not just the project',description:'Each task chooses its own path. Research can fan out to independent targets; a small known change can skip research and use a compact plan. Flash models do the routine work.',lanes:[['{host}','Goal owner & uncertainty fallback','host'],['Task runtime','Evidence, dependencies & checks','runtime'],['Jev','Route this task at decision points','jev'],['Flash workers','GLM / DeepSeek; Kimi when deeper','worker']],initial:'tstart',nodes:[
n('tstart',0,0,'host','A task becomes ready','Implementation or research outcome','amaleh / task entry (planned)','Task objective, acceptance criteria, and available evidence',['Keep the main model responsible for the requested outcome.','A research task may finish with evidence; it does not have to become a code change.'],'A focused task and its completion condition.','start'),
n('tstate',1,0,'runtime','Build current task state','Known facts, gaps, candidates, tools','amaleh / task state (planned)','Task, artifacts, dependencies, and eligible model pools',['Filter for required tools and modalities.','Resolve current stable GLM/DeepSeek Flash IDs at run start, then record exact choices.','Reuse valid decisions when neither state nor question has changed.'],'A small decision packet for this task.'),
n('troute',2,0,'jev','Does this task need research?','Choose one or several useful actions','amaleh / decisions.task-route (planned)','Task requirements, known facts, evidence gaps, and action candidates',['Choose source reading, web search, scratch experiment, compact plan, or direct execution.','Select several independent research targets when needed.','Choose the eligible Flash worker; select Kimi only for a supported need for deeper work.'],'Task route and bounded target briefs.'),
n('tsource',3,1,'worker','Inspect source code','GLM / DeepSeek Flash','amaleh / source-research brief (planned)','Specific files, symbols, behavior question, or failing trace',['Read relevant code, callers, and tests.','Return exact locations and observed behavior.','Do not expand into unrelated repository archaeology.'],'Source-backed findings and unresolved facts.'),
n('tweb',3,2,'worker','Search primary sources','GLM / DeepSeek Flash + retrieval','amaleh / web-research brief (planned)','A question needing current external evidence',['Search authoritative documentation and inspect the relevant pages.','Independent questions can run concurrently.','Return citations, dates, and contradictions.'],'Source-linked findings for this task.'),
n('tscratch',3,3,'worker','Run a scratch experiment','GLM / DeepSeek Flash + tools','amaleh / experiment brief (planned)','One uncertainty and the smallest experiment that can answer it',['Create an isolated scratchpad, reproduction, or prototype.','Run it and return observations with exact commands/results.','Keep exploratory artifacts separate from production code; integrate only justified changes.'],'Measured evidence; not an invented future feature.'),
n('tfallback',0,2,'host','Jev uncertain → host decides','No routine user interruption','amaleh / host fallback (planned)','Task question and available evidence',['Make the bounded decision when Jev cannot.','Record the fallback and continue the task.'],'A route or next action recorded against this task.'),
n('tcollect',1,4,'runtime','Gather target results','Independent results can arrive separately','amaleh / evidence collection (planned)','Source, web, and experiment artifacts',['Archive originals; deduplicate identical evidence.','Wait only for findings this task actually needs.','Unrelated ready tasks keep progressing.'],'Updated task evidence and remaining gaps.'),
n('tassess',2,4,'jev','Enough evidence for the next step?','Plan, execute, finish research, or narrow a gap','amaleh / decisions.task-evidence (planned)','New findings plus this task acceptance condition',['Research-only outcome satisfied? Return it to the host.','Implementation understood? Proceed with a compact plan or execution.','A real gap remains? Choose the next bounded target; repeated failure can escalate.'],'The next task-specific action; no fixed research ceremony.'),
n('tplan',3,5,'worker','Write a compact plan if useful','Flash worker; same session can execute','amaleh / compact-plan brief (planned)','Known change, relevant files, acceptance checks',['For a small task, write the few steps and checks that matter.','No mandatory separate spec, plan file, or extra planning agent.','Reuse an existing sufficient plan.'],'A small executable brief, or the requested plan itself.'),
n('timplement',3,6,'worker','Do the actual work','GLM / DeepSeek Flash by default','amaleh / implementation brief (planned)','Sufficient evidence and appropriate plan depth',['Implement or carry out the selected task.','Run relevant checks and report concrete artifacts.','Surface a newly discovered decision point with evidence; do not call Jev for every mechanical edit.'],'Changes, receipts, or a new bounded question.'),
n('tverify',1,7,'runtime','Check the actual result','Exact checks remain deterministic','amaleh / task verification (planned)','Artifacts and required test/check receipts',['Run the required task checks and record the exact revision.','A failed check cannot be overruled by a model.','Repair repeats re-enter decision routing with new evidence.'],'Verified task result or actionable failure evidence.'),
n('tdeep',3,8,'worker','Deeper work when justified','Kimi K3; main model stays in charge','amaleh / deeper-work brief (planned)','Complexity evidence, unresolved findings, or failed Flash attempt',['Handle the specific part needing more depth.','A known difficult task can route here directly; a cheap failure is not mandatory.','Return to the ordinary verification and handoff path.'],'Focused deeper work, not an automatic all-task upgrade.'),
n('treturn',0,9,'host','Return to the main agent','Inspect evidence; integrate or deliver','amaleh / task handoff (planned)','Verified changes or research findings with artifact references',['Accept only outcomes supported by evidence.','Integrate compatible changes and unlock dependent tasks.','The next task receives its own Jev routing decision.'],'Task outcome accepted or a precise repair request.','end')
],edges:[e('tstart','tstate','task'),e('tstate','troute','current evidence'),e('troute','tsource','source target'),e('troute','tweb','web target'),e('troute','tscratch','experiment target'),e('troute','tplan','small / known task'),e('troute','timplement','already sufficient'),e('troute','tfallback','uncertain','fallback'),e('tfallback','tstate','host decision','return'),e('tsource','tcollect','source findings','return'),e('tweb','tcollect','web findings','return'),e('tscratch','tcollect','observations','return'),e('tcollect','tassess','new evidence'),e('tassess','troute','remaining gap','fallback'),e('tassess','tplan','compact plan'),e('tassess','timplement','ready to execute'),e('tassess','treturn','research complete','return'),e('tplan','timplement','implementation requested'),e('tplan','treturn','plan-only requested','return'),e('timplement','tverify','artifacts'),e('tverify','troute','failure / new decision','fallback'),e('tverify','treturn','passed','return'),e('troute','tdeep','justified deeper work'),e('tdeep','tverify','deeper result','return')]};

views.review={title:'Fresh eyes, different model, bounded loop',description:'DeepSeek writes → GLM reviews. GLM writes → DeepSeek reviews. Group relevant lenses into one fresh pass; escalate after two repair cycles instead of repeating the same loop.',lanes:[['{host}','Own acceptance & escalation','host'],['Runtime','Exact evidence & loop counters','runtime'],['Jev','Choose lenses; triage findings','jev'],['Implementer','Flash → Kimi when escalated','worker'],['Independent reviewer','Opposite-family, fresh context','worker']],initial:'rauthor',nodes:[
n('rauthor',3,0,'worker','Work is ready for review','DeepSeek or GLM Flash author','amaleh / task implementation (planned)','Task intent and bounded implementation brief',['Finish a coherent change and run relevant checks.','Return actual artifacts; do not pre-write the reviewer verdict.'],'Authored change and check receipts.','start'),
n('rfreeze',1,0,'runtime','Pin the review evidence','Base + current revision + task intent','amaleh / review snapshot (planned)','Diff, changed files, standards, consumers, and test output',['Keep exact reviewed content and dependency hashes.','Share factual source maps, not author reasoning.','Reviewer tools are read-only; review is separate from repair.'],'Clean reviewer packet with retrievable sources.'),
n('rlenses',2,1,'jev','Select relevant lenses','Several lenses can share one reviewer','amaleh / decisions.review-plan (planned)','Actual changed behavior, task criteria, risk triggers',['Baseline: requirements/scope, correctness, omission, standards/simplicity, kept as separate sections.','Add money/error paths, contracts, visual/a11y, security, migrations, or other lenses only when supported.','One default reviewer; a sensitive change can add one focused reviewer in parallel.'],'A bounded review plan and eligible opposite-family model.'),
n('rpeer',4,1,'worker','Fresh opposite-model review','DeepSeek → GLM · GLM → DeepSeek','amaleh / review brief adapted from fresh-review + Matt Pocock','Pinned diff, intent, standards, current files, relevant callers, receipts',['Read with a clean context and no implementer reasoning transcript.','Trace actual affected consumers; missing changes may be outside the diff.','Report concrete reachable failures. Label code-smell judgment calls and inherited issues.'],'Separate lens findings with file, scenario, evidence, consequence, and fix.'),
n('rfocus',4,2,'worker','Optional focused reviewer','Parallel only when the change warrants it','amaleh / targeted lens brief adapted from fresh-review','Specific sensitive behavior and evidence needed for that lens',['Example: charge calculation and actual silent-error paths.','Bundle related lenses; do not create one agent per lens.','Preserve required coverage and all real findings; limit dispatch overhead, not evidence.'],'Focused findings in parallel with the baseline pass.'),
n('rledger',1,3,'runtime','Collect one finding ledger','Deduplicate claims, preserve evidence','amaleh / review ledger (planned)','Fresh review reports and relevant check results',['Retain separate Spec and Standards coverage and original reports.','Group duplicate claims and record open/resolved/refuted dispositions.','No finding disappears merely to shorten the report.'],'One consolidated actionable set tied to the reviewed revision.'),
n('rtriage',2,3,'jev','Triage against evidence','Real blocker, supported fix, or out of scope','amaleh / decisions.findings (planned)','Finding scenarios, scope, actual guards, and tests',['Assess relevance and support; do not manufacture future requirements.','Keep unrelated inherited issues visible without automatic scope expansion.','A demonstrated failed check cannot be waved through by confidence.'],'Supported fixes, gaps needing evidence, or proceed recommendation.'),
n('rresolve',0,4,'host','Resolve disputed findings','One focused evidence check if needed','amaleh / finding resolution (planned)','Serious uncertainty or conflicting suggested fixes',['Inspect guards, callers, and real repros; batch related disputes.','Do not spawn a skeptic per finding or a mandatory synthesis team.','Record a reason and evidence for every refutation or deferral.'],'Resolved repair instructions or a justified next investigation.'),
n('rguard',1,4,'runtime','Repair counter / exit gate','0 → 1 → 2; before 3, escalate','amaleh / review-loop guard (planned)','Open blockers, prior attempts, evidence of progress',['No open blockers and required checks pass: accept.','At most two ordinary Flash repair cycles by default.','Persist counts across commits, restart, and superficial task renames; no silent resets.'],'Accept, repair, or mandatory strategy escalation.'),
n('rfix',3,5,'worker','Repair the consolidated findings','Flash repair cycle 1 or 2','amaleh / repair brief (planned)','Actionable findings and exact evidence',['Fix the root cause within scope.','Run affected checks.','Do not independently rewrite the plan for reviewer preferences.'],'Repair delta and new check receipts.'),
n('rrecheck',4,5,'worker','Recheck the delta & affected behavior','Do not restart the entire lens library','amaleh / targeted re-review (planned)','Repair delta, finding ledger, and affected callers',['Verify resolved findings and regressions introduced by the fix.','Retain clean conclusions only while their evidence remains valid.','No automatic full fresh-review over unchanged code.'],'Updated finding states and actual verification evidence.'),
n('rescalate',3,6,'worker','Escalate to Kimi K3','Before third Flash repair; earlier if stuck','amaleh / deeper diagnosis (planned)','Failure history, concrete blockers, and relevant evidence',['Diagnose the repeated failure or wrong contract.','One focused diagnosis/repair cycle; do not repeat the same cheaper loop.','If resolved, return through independent verification.'],'A deeper correction or a concrete unresolved root cause.'),
n('rdeepcheck',4,6,'worker','Verify the deeper correction','Independent capable reviewer + tests','amaleh / escalation verification (planned)','Kimi correction, original requirements, blocker evidence',['Check the actual fix with a different eligible model family.','Run required checks; do not accept because an expensive model wrote it.'],'Verified correction or unresolved evidence for host takeover.'),
n('rtakeover',0,7,'host','Main model takes over diagnosis','One Kimi cycle still unresolved','amaleh / replan escalation (planned)','Full repair history and surviving evidence',['Change diagnosis, task boundaries, or upstream contract as needed.','Preserve escalation ancestry; do not silently reset the Flash loop.','Continue authorized work; only real external blockers need user intervention.'],'A recorded new strategy, followed by independent verification.'),
n('raccept',0,8,'host','Accept the verified task','Main agent integrates; dependents proceed','amaleh / acceptance (planned)','Resolved blockers and passing required evidence',['Integrate the coherent result and unlock dependent work.','At integration, review new cross-task interactions instead of repeating unchanged task reviews.','A loop limit is never permission to ship a known failure.'],'Verified handoff to the main workflow.','end')
],edges:[e('rauthor','rfreeze','artifact + checks','return'),e('rfreeze','rlenses','review facts'),e('rlenses','rpeer','baseline pass'),e('rlenses','rfocus','sensitive behavior'),e('rpeer','rledger','findings','return'),e('rfocus','rledger','focused findings','return'),e('rledger','rtriage','evidence'),e('rtriage','rguard','disposition'),e('rtriage','rresolve','serious dispute','fallback'),e('rresolve','rguard','verified resolution'),e('rguard','rfix','cycles < 2'),e('rfix','rrecheck','repair delta'),e('rrecheck','rledger','updated findings','return'),e('rguard','rescalate','limit / no progress','fallback'),e('rescalate','rdeepcheck','deeper correction'),e('rdeepcheck','raccept','verified','return'),e('rdeepcheck','rtakeover','still unresolved','fallback'),e('rtakeover','rfreeze','changed strategy'),e('rguard','raccept','clear + checks pass','return')]};

// Keep the overview and task drill-down connected to the same review policy.
for(const id of ['review','triage','integrate','accept','completion','deliver']) views.flow.nodes.find(node=>node.id===id)!.row+=1;
views.flow.nodes.push(n('reviewplan',3,4,'jev','Select review lenses','One fresh pass; focused extra if needed','amaleh / decisions.review-plan (planned)','Change evidence and actual risk triggers',['Choose relevant lenses and a different-family reviewer.','Group questions to avoid one agent per lens.'],'Scoped fresh reviewer brief.'),n('peer',4,5,'worker','Independent cross-model review','DeepSeek ↔ GLM Flash','amaleh / adapted fresh-review + Matt Pocock review','Clean evidence packet, no author reasoning',['Read actual changes and affected consumers.','One consolidated findings list; two repair cycles before escalation.','See Review & escalation for the complete loop.'],'Evidence-backed findings returned to the main agent.'));
views.flow.edges=views.flow.edges.filter(edge=>!(edge.from==='receipts'&&edge.to==='review'));
views.flow.edges.push(e('receipts','reviewplan','review facts'),e('reviewplan','peer','lenses + reviewer'),e('peer','review','fresh findings','return'));
const overviewReview=views.flow.nodes.find(node=>node.id==='review')!;
overviewReview.skill='amaleh / review coordination (planned); adapted fresh-review and Matt Pocock lenses';
overviewReview.actions=['Inspect actual artifacts and independent findings.','Resolve conflicting fixes or serious uncertain findings using evidence.','Preserve the repair counter: two Flash cycles, then Kimi diagnosis; a defect that survives a repair goes up at once; unresolved after Kimi goes to the main model.'];
views.task.nodes.push(n('treview',3,7,'worker','Fresh cross-model review','DeepSeek ↔ GLM Flash','amaleh / adapted review (planned)','Pinned artifacts, criteria, and check receipts',['Review with the opposite model family in a fresh context.','Group relevant lenses; after a repair the same reviewer verifies only the repair diff.','Escalate to Kimi after two Flash repair cycles, or at once when a defect survives a repair; preserve the counter on every return.'],'Verified findings or a reviewed task result.'));
views.task.edges=views.task.edges.filter(edge=>!(edge.from==='tverify'&&edge.to==='treturn'));
views.task.edges.push(e('tverify','treview','passing check receipts'),e('treview','treturn','review passed','return'),e('treview','troute','findings; bounded loop','fallback'));
const skillsReview=views.skills.nodes.find(node=>node.id==='sreview')!;
skillsReview.title='Coordinate cross-model review';
skillsReview.skill='amaleh / adapted fresh-review + Matt Pocock lenses (planned)';
skillsReview.actions=['Dispatch a fresh opposite-family reviewer; keep Spec and Standards results separate.','Reuse relevant fresh-review lenses without its full fan-out and repeated ceremony.','Two Flash repair cycles, then Kimi diagnosis; one unresolved Kimi cycle triggers main-model takeover.'];
views.skills.description='Amaleh owns orchestration. Review adapts fresh-review lenses and Matt Pocock’s two axes; it does not blindly invoke both full pipelines. External skills remain task-specific.';

// Optional discovery is a task decision, never an unconditional project phase.
views.discovery={title:'Decide whether to grill, brainstorm, research, or proceed',description:'Jev chooses the mode from actual gaps. The main model holds the conversation; Flash workers gather facts. User intent stays with the user, and settled answers survive handoffs.',lanes:[['You','Intent & meaningful tradeoffs','user'],['{host}','Conversation & recommendations','host'],['Runtime / Flash workers','Facts & durable decisions','runtime'],['Jev','Route and reassess','jev']],initial:'dstart',nodes:[
n('dstart',1,0,'host','Understand the request','At entry or a newly discovered decision','amaleh / discovery entry (planned)','Request, prior answers, scope and repository facts',['Reuse settled intent and acceptance criteria.','Describe the concrete uncertainty; do not manufacture questions.'],'Known facts and unresolved decisions.','start'),
n('droute',3,0,'jev','Which discovery mode helps?','Proceed · research · grill · brainstorm','amaleh / decisions.discovery (planned)','Intent gaps, factual gaps, candidate approaches and existing authorization',['Clear outcome and sufficient evidence: proceed.','Missing facts: research. Ambiguous constraints or shaky assumptions: focused grilling.','Open solution or experience direction: compare approaches through brainstorming.','Modes can be combined only where each resolves a real gap; uncertainty goes to the host.'],'A bounded mode, questions and exit condition.'),
n('dfacts',2,1,'worker','Find facts before asking','GLM / DeepSeek Flash footwork','amaleh / targeted research (planned)','Specific unknowns in source, docs, assets or behavior',['Read source, search primary sources or run a small scratch experiment.','Parallelize independent targets and keep unrelated ready work moving.','Do not ask the user for facts available through tools.'],'Evidence with retrievable sources.'),
n('dgrill',1,2,'host','Focused grill-me style interview','Challenge assumptions that affect the result','amaleh / focused-grilling adaptation (planned)','Unsettled intent, constraints and factual evidence',['Map the decision tree and ask only questions whose prerequisites are settled.','Use small rounds of independent questions with a recommendation and consequence.','Defer dependent questions; do not explore hypothetical branches outside scope.'],'Concrete questions for the user.'),
n('dbrain',1,3,'host','Explore plausible approaches','Superpowers-inspired brainstorming','amaleh / focused-brainstorming adaptation (planned)','Open design choice, known constraints and actual use case',['Present two or three useful approaches with tradeoffs and a recommendation.','Use HTML or visuals when they make the choice clearer.','Scale detail to the decision; avoid mandatory documents and repeated approval stages.'],'A focused design choice the user can assess.'),
n('duser',0,4,'user','Resolve intent and tradeoffs','Only decisions that need your input','amaleh / user clarification (planned)','Focused questions or concrete design options',['Answer, correct the assumptions, or delegate the choice explicitly.','Only dependent work waits for a necessary answer; elapsed time is not consent.'],'Answers or explicit delegated discretion.'),
n('drecord',2,4,'runtime','Persist the decision contract','Answers, constraints, non-goals, acceptance','amaleh / decision ledger (planned)','Evidence, user answers and prior decision ancestry',['Preserve decisions in subagent briefs and compaction checkpoints.','Record unresolved questions and the work each blocks.','Reopen a settled choice only when changed intent or new evidence invalidates it.'],'Versioned contract with precise remaining gaps.'),
n('dready',3,5,'jev','Ready for useful execution?','Check the exit condition','amaleh / decisions.discovery-exit (planned)','Updated contract and the decisions required by the next task',['Proceed when the outcome, material constraints and acceptance checks are sufficient.','If a gap remains, name that gap and select only the useful next mode.','Never invent user agreement or use confidence to bypass missing required input.'],'Proceed or one specific unresolved decision.'),
n('dexit',1,6,'host','Return to the work graph','Compact plan → ready work → verification','amaleh / discovery handoff (planned)','Sufficient contract, authorization and evidence',['Reflect the agreed understanding briefly; reuse existing confirmation.','For newly co-designed intent, obtain confirmation before dependent implementation; no redundant plan/spec approval ladder.','Continue execution in the same run once required answers are present.'],'Actionable task brief; no mandatory brainstorming for clear tasks.','end')
],edges:[e('dstart','droute','request + gaps'),e('droute','dfacts','missing facts','return'),e('dfacts','drecord','research evidence'),e('droute','dgrill','test assumptions','return'),e('droute','dbrain','explore options','return'),e('droute','dexit','already clear','return'),e('dgrill','duser','focused questions','return'),e('dbrain','duser','options + tradeoffs','return'),e('duser','drecord','answers'),e('drecord','dready','updated contract'),e('dready','droute','specific gap remains','fallback'),e('dready','dexit','sufficient','return'),e('droute','dstart','uncertain → host','fallback')]};
for(const [key,routeId,returnId,nodeId,lane,row] of [['flow','scope','scope','discovery',1,2],['task','troute','tstate','tdiscovery',0,3]] as const){
 const view=views[key],route=view.nodes.find(node=>node.id===routeId)!;
 route.actions.unshift('Choose focused grilling for unresolved intent/assumptions or brainstorming for open design alternatives; see Discovery decisions.');
 view.nodes.push(n(nodeId,lane,row,'host','Grill / brainstorm when needed','Main model + user; Flash gathers facts','amaleh / discovery adaptations (planned)','A concrete question selected by Jev',['Use the Discovery decisions graph for the full conversation loop.','Preserve answers; block only dependent work.','Return once the required intent and acceptance decisions are settled.'],'Updated task contract and evidence.'));
 view.edges.push(e(routeId,nodeId,'intent / design gap','return'),e(nodeId,returnId,'settled answers'));
}
views.flow.nodes.find(node=>node.id==='scope')!.sub='Proceed, research, grill, or brainstorm';
views.task.nodes.find(node=>node.id==='troute')!.title='What does this task need next?';
views.skills.nodes.find(node=>node.id==='sskill')!.actions.push('Select Amaleh focused-grilling or focused-brainstorming adaptations for genuine intent/design gaps; main model leads the user conversation.');

// Amaleh owns the whole workflow. Source skills inform design, never runtime dependencies.
const builtins:Record<string,string>={plan:'planning and architecture',coding:'implementation',specialists:'specialist work',accept:'acceptance verification',sfront:'frontend design',svision:'visual inspection',sarchitecture:'architecture',sreview:'review coordination',sentry:'entry',sskill:'module selection'};
for(const view of Object.values(views)) for(const node of view.nodes){
 node.skill=`amaleh / ${builtins[node.id] || node.skill.replace(/^amaleh\s*\/\s*/,'').split(';')[0].replace(/adapted.*$/,'built-in review').replace(/\(planned\)/g,'').trim()} (built-in, planned)`;
}
const moduleSelector=views.skills.nodes.find(node=>node.id==='sskill')!;
moduleSelector.title='Choose built-in capabilities';moduleSelector.sub='No external skill dependencies';
moduleSelector.input='Task purpose, current run state, bundled module descriptions and model cards';
moduleSelector.actions=['Select only the Amaleh modules needed for the next action; one entry point owns their handoffs.','Discovery, specification, planning, research, implementation, review and recovery are bundled.','External skills supplied research ideas; their installation and invocation are not required.'];
views.skills.title='One skill, built-in capabilities, configurable models';
views.skills.description='Amaleh owns the complete flow for small tasks and large multi-phase features. Models and tools are execution services; no external skill is required.';
views.skills.nodes.find(node=>node.id==='score')!.actions=['Bundle discovery, specification, planning, graph scheduling, implementation, review, documentation and recovery.','Load only the task-relevant bundled instructions to keep context small.','Use Bun first and Node fallback; model/API/tool dependencies remain explicit.'];
views.skills.nodes.find(node=>node.id==='sreview')!.actions=['Use the bundled fresh cross-model review policy and separate Spec and Standards findings.','Two Flash repair cycles, then deeper diagnosis and main-model takeover if unresolved.','Main model owns acceptance; no external review skill or issue tracker is required.'];
views.lifecycle={title:'One durable flow, from a small fix to a large feature',description:'Every invocation loads or creates durable run state, reconciles reality, and selects the next useful action. Phases organize large work; they do not force every task through a ceremony.',lanes:[['{host}','Intent, contracts & acceptance','host'],['Durable runtime','State, ownership & dependencies','runtime'],['Jev','Next useful action','jev'],['Workers','Independent ready work','worker']],initial:'lentry',nodes:[
n('lentry',0,0,'host','Start / resume Amaleh','Same entry point in any session','amaleh / entry (built-in, planned)','Request plus workspace/run identity',['Find the matching run or create a new one.','A fresh session need not contain the old chat; the canonical skill and stored run provide recovery.','Disambiguate genuinely ambiguous runs instead of guessing.'],'Selected run identity.','start'),
n('lload',1,0,'runtime','Load durable state','Chat is not the source of truth','amaleh / recovery (built-in, planned)','Versioned run records and artifact references',['Restore intent, decisions, contracts, task graph, phase outcomes and next actions.','Restore reviews, escalation ancestry, evidence hashes, usage and blocked reasons.','Read a compact index first; retrieve detailed evidence only for active work.'],'Restored work graph and relevant context.'),
n('lreconcile',1,1,'runtime','Reconcile with reality','No blind restart or stale success','amaleh / reconciliation (built-in, planned)','Saved state, actual files, processes, sessions and operation receipts',['Distinguish live workers from abandoned work; recover only expired ownership.','Revalidate affected evidence when files or dependencies changed.','Before replaying an interrupted side effect, inspect its durable receipt and actual result; ambiguous outcomes require resolution.'],'Current eligible actions and recoverable failures.'),
n('lnext',2,1,'jev','What does this run need now?','Discover · specify · plan · work · repair · finish','amaleh / decisions.next-action (built-in, planned)','Current contracts, gaps, ready tasks and legal actions',['Choose the next useful built-in capability from evidence.','Small clear tasks may go directly to execution with a short brief.','Large work may expand its graph, resolve an interface, research a gap or execute ready tasks.','Uncertain selection returns to the host; code enforces dependencies and verification.'],'Bounded next action, never a mandatory phase restart.'),
n('lcontract',0,2,'host','Discover / specify / plan','All inside Amaleh','amaleh / intent and planning (built-in, planned)','Actual missing decisions and existing agreed intent',['Use focused grilling or brainstorming only for real gaps.','Synthesize a compact spec with outcomes, non-goals, interfaces and acceptance criteria from known decisions.','For large features, define phase outcomes and a dependency graph; detail ready work without inventing far-future requirements.','Maintain human-facing design and graphs in HTML; no to-spec invocation or issue-tracker setup is needed.'],'Durable contract and appropriately sized work graph.'),
n('lschedule',1,3,'runtime','Dispatch dependency-ready work','Parallelism follows actual independence','amaleh / scheduler (built-in, planned)','Validated tasks, interface contracts and resource ownership',['Reject invalid graphs and conflicting writes before dispatch.','Use isolated workspaces for independent changes; retain shared-resource/integration locks.','Phase labels do not impose a global barrier; start work whenever its real prerequisites pass.'],'Focused briefs and tracked worker ownership.'),
n('lwork',3,3,'worker','Research / implement / review','Flash footwork; bounded escalation','amaleh / bundled task capabilities (built-in, planned)','Focused context and acceptance checks',['Execute the task-specific route and return retrievable artifacts.','Use independent cross-model review and the persistent repair counter.','Run relevant checks in isolation; integration checks run against combined content.'],'Changes, findings and exact check receipts.'),
n('lcheckpoint',1,4,'runtime','Persist every material transition','Recover even without a final chat message','amaleh / durable journal (built-in, planned)','Worker results, decisions and side-effect receipts',['Write schema-versioned records with atomic checkpoint replacement and recoverable event ordering.','Save before dispatch and after results; preserve original artifacts and operation identities.','Keep completed and blocked work, remaining dependencies and next actions visible; never infer completion from phase labels.'],'Recoverable checkpoint independent of session context.'),
n('laccept',0,5,'host','Verify feature-wide outcomes','Task success alone is insufficient','amaleh / integration and acceptance (built-in, planned)','Integrated content, original intent and retained evidence',['Check cross-task interactions and end-to-end acceptance criteria.','Update affected repository documentation and the HTML status/design views.','Return real gaps to the graph; finish only when required outcomes and checks are satisfied.'],'Verified completion or concrete remaining work.'),
n('lend',0,6,'host','Deliver / checkpoint a real blocker','Continue until complete or intervention needed','amaleh / finish and recovery (built-in, planned)','Verified outcome or genuine external blocker',['Report actual completion with evidence.','For exhausted credits or an external blocker, preserve a resume point and explain the needed intervention.','Clearing a session does not run work in the background; re-invoking Amaleh resumes from stored state.'],'Completed run or resumable blocked run.','end')
],edges:[e('lentry','lload','run identity'),e('lload','lreconcile','stored state'),e('lreconcile','lnext','eligible actions'),e('lnext','lcontract','missing contract','return'),e('lcontract','lcheckpoint','decisions + graph'),e('lnext','lschedule','ready work','return'),e('lschedule','lwork','dispatch'),e('lwork','lcheckpoint','artifacts','return'),e('lcheckpoint','lreconcile','next transition','fallback'),e('lnext','laccept','acceptance ready','return'),e('laccept','lcheckpoint','real gaps'),e('laccept','lend','verified'),e('lreconcile','lend','external blocker','fallback'),e('lend','lload','later resume','fallback')]};
views.flow.nodes.find(node=>node.id==='start')!.actions.push('Restore durable state through the Large work & resume path before selecting the next action.');
views.flow.nodes.find(node=>node.id==='plan')!.actions.push('Use built-in specification and phase planning for large features; no external skill or tracker dependency.');

views.effort={title:'Same main model, higher effort only when needed',description:'Medium coordinates and integrates. Jev may select a high-effort pass for unresolved architecture, diagnosis or final review. Record real execution, then return to baseline; this is separate from changing worker models.',lanes:[['{host}','Baseline coordinator','host'],['Runtime','Capabilities & execution receipts','runtime'],['Jev','Stay or increase effort','jev'],['Same exact host model','Bounded higher-effort pass','host']],initial:'ebase',nodes:[
n('ebase',0,0,'host','Coordinate / integrate / verify','Medium baseline, unless user overrides','amaleh / baseline effort','Current task, observed session setting and user preference',['Keep routine orchestration at baseline.','Identify a concrete unresolved architecture, diagnosis or acceptance question.'],'Evidence for a bounded effort decision.','start'),
n('ecaps',1,0,'runtime','Verify supported effort levels','Never infer capabilities from family alone','amaleh / effort-configure','Actual host model, baseline, supported ordered levels and mechanisms',['Record verified capabilities and their source.','Distinguish session adjustment from same-model subagent execution.'],'Legal effort options and mechanisms.'),
n('eselect',2,1,'jev','Baseline sufficient or higher effort?','Normally medium → high, only if justified','amaleh / decide + effort-request','Bounded question, host model, baseline and actual evidence',['Choose baseline if ordinary execution is sufficient.','Choose a supported higher effort for substantive unresolved complexity.','Uncertainty returns to the main model; no mandatory high-effort final-review ceremony.'],'A recorded level selection; it is not yet an applied setting.'),
n('elaunch',1,2,'runtime','Dispatch / apply and record receipt','Exact model remains unchanged','amaleh / effort-start','Selected level, verified mechanism, native execution identity',['Use a supported session setting, or one native same-model pass at the chosen effort.','No instruction-only pretend escalation.','Reject model substitutions and unsupported levels.'],'Actual execution/configuration evidence.'),
n('ehigh',3,2,'host','Architecture / diagnosis / final review','Same model at high effort','amaleh / bounded host effort pass','Focused evidence and a specific question',['Perform only the part needing deeper reasoning.','Return conclusions, evidence and remaining uncertainty.','Use high rather than automatically jumping to maximum.'],'A retrievable result for the baseline coordinator.'),
n('ereturn',0,3,'host','Inspect result; return to baseline','Medium resumes normal coordination','amaleh / effort-finish','Finished execution, saved result and baseline confirmation',['Restore the actual baseline for session changes.','For separate passes, record that the coordinator setting never changed.','Pending effort executions survive resume and prevent premature completion.'],'Continue the same work graph.','end')
],edges:[e('ebase','ecaps','observed context'),e('ecaps','eselect','eligible levels'),e('eselect','ebase','baseline sufficient','return'),e('eselect','elaunch','higher effort justified'),e('elaunch','ehigh','same model + high'),e('ehigh','ereturn','result + evidence','return'),e('ereturn','ebase','continue','return')]};
views.flow.nodes.find(node=>node.id==='intake')!.actions.push('Use medium as the intended coordinator baseline unless the user explicitly selects another supported effort.');
views.flow.nodes.find(node=>node.id==='accept')!.actions.push('For unresolved consequential review questions, use the conditional same-model effort path; see Host effort.');
views.review.nodes.find(node=>node.id==='rtakeover')!.actions.push('Jev may request the same main model at higher supported effort; record actual execution and return to baseline.');

// The default view describes executable boundaries; other tabs retain design policy detail.
for(const view of Object.values(views))view.description='Design policy view (not all steps are automatic). '+view.description;
views.runtime={title:'The implemented path: commands, decisions and returns',description:'The host drives the loop. Code chooses legal next actions; Jev chooses eligible models and host-requested semantic options. Each node names the actual command or bundled instruction.',lanes:[['{host}','One Amaleh invocation','host'],['Runtime','State and exact gates','runtime'],['Jev','Bounded choices','jev'],['Subagents','pi / OpenRouter','worker']],initial:'xentry',nodes:[
n('xentry',0,0,'host','START / resume','Load Amaleh once','amaleh / SKILL.md; list, start, resume','Request and actual host identity',['Find matching durable work.','Resume checks ownership and stale acceptance before continuing.'],'Run and next action.','start'),
n('xnext',1,0,'runtime','Read legal next actions','Deterministic; no Jev call','amaleh / next','Run state and evidence',['Return focus action and independent ready work.','The host executes the action and loops; this is not an unattended scheduler.'],'Focus plus parallel opportunities.'),
n('xplan',0,1,'host','Resolve gaps / shape graph','Small task or multiple phases','amaleh / planning.md; decide, plan, amend','Real intent gaps and current code',['Call decide for meaningful research, discovery or planning choices.','Ask focused questions only where intent is missing.','Record tasks and actual dependency edges.'],'Contract, graph and registered checks.'),
n('xmeaning',2,1,'jev','Choose a semantic option','Host supplies evidence and choices','amaleh / decide; host-decision','Bounded options, actual evidence',['Judge research/discovery route, review lens or claim support.','Uncertainty returns to the host for recorded fallback.'],'Decision; code still enforces exact gates.'),
n('xroute',1,2,'runtime','Prepare isolated work + route','Automatic inside worker/reviewer','amaleh / route; worker; reviewer','Task, pool, modalities and current catalog',['Host prepares the isolated workspace.','Reject unmet dependencies, capacity and conflicts before catalog/Jev calls.','Filter current exact eligible models; exclude floating aliases.','Reviewer candidates exclude author family.'],'Eligible model cards and routing scope.'),
n('xjev',2,2,'jev','Select suitable model','Flash defaults; configured specialists','amaleh / automatic model routing','Task, candidate capability/price and suitability evidence',['Choose a candidate or reassess.','Confidence below threshold prevents launch.','Deep repair requires Kimi; host depth returns host takeover.'],'Recorded choice or pending host decision.'),
n('xfallback',0,3,'host','Resolve uncertainty / pool gap','No silent model override','amaleh / host-decision; pools; route','Pending choice or no eligible models',['Record an eligible fallback with evidence, or revise the task/pool.','Repeat original launch input; reuse the settled choice.'],'Launchable route or concrete blocker.'),
n('xlaunch',3,3,'worker','Tracked isolated execution','Model chosen by route','amaleh / worker; pi adapter','Focused brief, task and allowed tools',['Consume route once with claim before spawning.','Execute bounded task; preserve session and original results.'],'Actual model, artifacts and process receipts.'),
n('xdirect',0,2,'host','Authorized host exception','No convenience bypass','amaleh / host-exception; claim; result','Explicit user request or exhausted persistent repair',['Claim with a single-use hostAuthorization and actual host identity.','For justified higher effort use effort-request/start/finish with real execution evidence.','Failed/unlaunched effort uses effort-reconcile.'],'Recorded changes and return to next.'),
n('xcheck',1,4,'runtime','Run registered checks','Prose is not a passing receipt','amaleh / check','Current workspace and check contract',['Record output, exit code and content fingerprint.','Failure returns to repair; changed content invalidates evidence.'],'Passing fresh evidence or repair cause.'),
n('xreview',3,5,'worker','Fresh independent review','Automatic opposite-family route','amaleh / reviewer; review','Criteria, actual sources, check receipts and lenses',['Route reviewer through xroute/xjev first.','Inspect actual behavior with read-only tools.','Native review can use review with actual identity and evidence.'],'Supported findings or fresh pass.'),
n('xrepair',2,6,'runtime','Repair / escalate','2 Flash cycles → Kimi → host','amaleh / repair; next','Blocking findings or failed check',['Persist repair ancestry.','Return to routing at the required depth.','Keep independent ready work visible throughout.'],'Repair task at enforced depth.'),
n('xaccept',1,6,'runtime','Accept verified task','Gate freshness and findings','amaleh / accept','Current review and required checks',['Reject missing/stale/failed checks and open blockers.'],'Accepted task, not yet integrated.'),
n('xintegrate',0,7,'host','Integrate and unlock dependents','Host performs actual integration','amaleh / integrated; check','Accepted changes and interaction inspection',['Record integration evidence after integrating.','Run required feature checks on combined content.','Return to next for newly ready dependencies.'],'Integrated markers and feature receipts.'),
n('xfinish',0,8,'host','Verify outcomes / finish','Host owns semantic acceptance','amaleh / decide; finish','Original criteria, all tasks and fresh integration checks',['Ask Jev about claim support where required by policy.','Code rejects incomplete work, pending decisions and active effort.'],'Verified outcome and durable completed run.','end'),
n('xrecover',0,5,'host','Recover actual interruption','No fake success or blind replay','amaleh / diagnose; resume; requeue','API/process error, ownership and original evidence',['Inspect diagnostics and reconcile actual side effects.','Top up or fix the real external blocker before resuming.','A cleared chat resumes from disk on the next invocation.'],'Reconciled state back to next.')
],edges:[e('xentry','xnext'),e('xnext','xplan','missing contract'),e('xplan','xmeaning','bounded question'),e('xmeaning','xplan','decision / fallback','return'),e('xplan','xnext','plan saved'),e('xnext','xroute','ready task'),e('xnext','xdirect','explicit exception'),e('xroute','xjev','eligible cards'),e('xroute','xnext','waiting prerequisite','return'),e('xroute','xfallback','no eligible model','fallback'),e('xjev','xfallback','uncertain / reassess','fallback'),e('xfallback','xroute','resolved / revised'),e('xjev','xlaunch','worker choice'),e('xlaunch','xcheck','result'),e('xdirect','xcheck','result'),e('xcheck','xroute','route reviewer'),e('xjev','xreview','reviewer choice'),e('xreview','xaccept','fresh pass'),e('xreview','xrepair','blocking finding','fallback'),e('xcheck','xrepair','failed check','fallback'),e('xrepair','xnext','required depth'),e('xaccept','xintegrate'),e('xintegrate','xnext','more work'),e('xintegrate','xmeaning','claim support'),e('xmeaning','xfinish','supported claims'),e('xlaunch','xrecover','process / service failure','fallback'),e('xjev','xrecover','service failure','fallback'),e('xnext','xrecover','missing workspace','fallback'),e('xrecover','xnext','reconciled','return')]};

views.parallel={title:'Parallel verification, individual completion',description:'The host dispatches the suggested independent batch; durable leases enforce shared capacity and conflicts. A completed task unlocks its dependents without waiting for unrelated slower work.',lanes:[['{host}','Dispatch and integration','host'],['Runtime','Frontier and active leases','runtime'],['Task A','Isolated workspace A','worker'],['Task B','Isolated workspace B','worker'],['Task C','Isolated workspace C','worker']],initial:'pstart',nodes:[
n('pstart',0,0,'host','Read next once','Focus plus all task opportunities','amaleh / next; parallelism.md','Current run state',['Inspect parallel.actions and parallel.independent.','The focus may already be in the batch; do not dispatch it twice.'],'Independent check/review candidates.','start'),
n('pfront',1,0,'runtime','Expose the verification frontier','Not only review[0]','amaleh / next.parallel','Every task stage and live owners',['Include checks/reviews beyond the first task.','Show repairs/integration for host handling.','Suggest only distinct nonconflicting workspaces within free slots.'],'Batch suggestion, not a reservation.'),
n('please',1,1,'runtime','Acquire actual execution slots','Worker + task check + pi review','amaleh / acquireActivity; claim','Current ownership and proposed execution',['Atomically reject duplicate task verification, conflicts and excess capacity.','Record coordinator and spawned child identity.','Keep checks within a single workspace serialized.'],'Durable lease before execution.'),
n('pa',2,2,'worker','Task A check / review','Runs concurrently when eligible','amaleh / check or reviewer','Own workspace, contract and lease',['Run actual check or independently routed pi review.','Retain output and content fingerprint.'],'Result returned independently.'),
n('pb',3,2,'worker','Task B check / review','May finish later than A','amaleh / check or reviewer','Own workspace, contract and lease',['Execute without waiting for unrelated A or C.','Shared-resource conflicts remain serialized.'],'Own evidence and completion time.'),
n('pc',4,2,'worker','Task C check / review','Bounded by available capacity','amaleh / check or reviewer','Own workspace, contract and lease',['Occupy one shared slot until completion or failure.','An active operation is visible to next and resume.'],'Own evidence and completion time.'),
n('pret',1,3,'runtime','Record and release individually','No whole-batch completion barrier','amaleh / result receipts; releaseActivity','Each process outcome',['Persist evidence, then release its lease in cleanup.','Refresh available capacity immediately.','No acceptance while task verification is active.'],'Fresh evidence and an available slot.'),
n('pmerge',0,3,'host','Accept and integrate ready result','Serial main-checkout boundary','amaleh / accept; integrated','Passed checks and independent review',['Integrate an accepted result while unrelated isolated work continues when safe.','Inspect actual interactions; do not parallelize conflicting integration writes.'],'Its actual dependents unlock.'),
n('pdep',2,4,'worker','Start an unlocked dependent','Does not wait for B and C','amaleh / worker','Integrated prerequisite and free slot',['Route and claim using actual dependencies.','Required checks/review still apply.'],'Next useful work overlaps the tail of the batch.'),
n('precover',1,5,'runtime','Reconcile interrupted ownership','Never duplicate a living child','amaleh / resume; diagnose; requeue','Lease and coordinator/child liveness',['Preserve ownership while either process is live.','Block abandoned verification for explicit reconciliation.','Original receipts and sessions remain available.'],'Safe continuation or a concrete blocker.'),
n('pend',0,6,'host','Finish verified feature','Integration checks remain serial','amaleh / check; finish','All integrated outcomes and required evidence',['Verify feature-wide interactions after integration.','Parallelism never changes the acceptance threshold.'],'Completed run.','end')
],edges:[e('pstart','pfront'),e('pfront','please'),e('please','pa','eligible A'),e('please','pb','eligible B'),e('please','pc','eligible C'),e('pa','pret','A returns','return'),e('pb','pret','B returns','return'),e('pc','pret','C returns','return'),e('pret','pmerge','each verified result'),e('pmerge','pdep','prerequisite ready'),e('pdep','pfront','continue'),e('pret','pfront','free slot','return'),e('please','precover','interruption','fallback'),e('precover','pfront','reconciled','return'),e('pmerge','pend','all outcomes integrated')]};

// Review method: one evidence contract, not an unbounded reviewer ladder.
views.review={title:'Review coverage before acceptance',description:'Host maps reachable behavior; one fresh reviewer inspects it. Code blocks incomplete coverage. Jev judges semantic choices. No automatic guarantee that evidence claims are true.',lanes:[['{host}','Impact map, probes, integration','host'],['Runtime','Durable evidence and hard gates','runtime'],['Jev','Bounded semantic judgment','jev'],['Fresh reviewer','Different model family','worker']],initial:'mstart',nodes:[
n('mstart',0,0,'host','Map the changed behavior','Start before the first review','amaleh / review method','Task and global outcomes, actual changes, repository standards',['Identify callers, consumers and trustworthy baseline/diff.','Enumerate reachable success, rejected preflight, failure, interruption and resume paths.','Mark irrelevant lenses with reasons; do not invent product requirements.'],'Concrete obligations and discriminating probes.','start'),
n('mcontract',1,1,'runtime','Build factual review packet','Criteria + required coverage IDs','amaleh / review-packet','Intent, decisions, task and dependency contracts',['Include registered commands, receipt refs and artifact directory.','Exclude author output, reasoning and proposed verdict.','Require each criterion/outcome plus Standards, Boundaries, Lifecycle, Parallelism and Integration.'],'Fresh factual contract; baseline and standards require inspection.'),
n('mjev',2,1,'jev','Choose relevant depth','Models and additional focused lenses','amaleh / decide; route','Current evidence and eligible options',['Choose an opposite-family reviewer.','Select extra depth only for a reachable risk.','Uncertainty returns to host; no confidence bypasses missing evidence.'],'One grouped pass by default.'),
n('mprobes',0,2,'host','Execute independent probes','Parallel with source inspection','amaleh / review-check; check','Registered commands and actual expected behavior',['Probe failure exits and consumer outcomes, not just the happy path.','Use isolated workspaces and existing shared capacity rules.','Archive real results; do not ask a read-only reviewer to run tests.'],'Observable behavioral evidence.'),
n('mpeer',3,2,'worker','Inspect source and evidence','One fresh cross-family reviewer','amaleh / reviewer','Factual packet, repository files, receipt artifacts',['Read applicable standards and affected consumers.','For every obligation: covered, finding, unreviewed or justified not-applicable.','Reference paths/results; request exact missing probes.'],'Findings plus structured coverage ledger.'),
n('mgate',1,3,'runtime','Coverage and freshness gate','No findings does not mean complete','amaleh / review; next; accept','Current fingerprint, registered checks, coverage ledger',['Reject malformed or duplicate coverage.','Block missing, unreviewed or finding coverage.','A prose report cannot replace the ledger; assertions still need host scrutiny.'],'Accept, targeted evidence gap, or defect triage.'),
n('mgap',0,4,'host','Resolve the exact gap','No repair counter increment','amaleh / review-evidence-needed','Missing evidence or unanswered obligation',['Inspect missing source or register/run a targeted probe.','Updated independent review records complete coverage.','Repeated uncertainty goes to host diagnosis/higher effort, not identical paid loops.'],'New evidence, preserved ancestry.'),
n('mtriage',2,4,'jev','Triage supported defects','Host resolves serious disputes','amaleh / decide; host-decision','Reachable scenario, actual evidence, consequence',['Group duplicate roots without losing evidence.','No judgment dismisses a failing required check.'],'Supported repair or evidence-backed correction.'),
n('mrepair',0,5,'host','Repair and recheck impact','2 Flash → 1 Kimi → host','amaleh / repair; effort','Confirmed defect and persistent counter',['Recheck changed behavior and affected consumers.','Retain valid conclusions; never copy stale evidence.','Change strategy on escalation.'],'Corrected result enters coverage gate again.'),
n('maccept',1,6,'runtime','Accept verified task','Fresh checks + complete declared coverage','amaleh / accept','Idle verification, valid dependencies, no blockers',['All registered checks must pass for current content.','Legacy incomplete review receipts cannot authorize acceptance.'],'Accepted task ready for host integration.'),
n('mintegrate',0,7,'host','Verify composed outcomes','Serial integration, actual consumer checks','amaleh / integrated; check; finish','Accepted tasks and whole-feature criteria',['Inspect interactions changed by composition.','Run integration checks and map each outcome to evidence.','Record new escaped-defect regression under its obligation.'],'Verified feature; no zero-bug guarantee.','end')
],edges:[e('mstart','mcontract'),e('mcontract','mjev'),e('mjev','mpeer','selected reviewer'),e('mcontract','mprobes','independent probes'),e('mprobes','mgate','receipts'),e('mpeer','mgate','ledger + findings','return'),e('mgate','mgap','missing coverage','fallback'),e('mgap','mprobes','targeted probe','return'),e('mgap','mpeer','focused inspection'),e('mgate','mtriage','real defect'),e('mtriage','mrepair','repair needed'),e('mrepair','mcontract','changed evidence','return'),e('mgate','maccept','coverage + checks pass'),e('maccept','mintegrate')]};

const $ = <T extends HTMLElement=HTMLElement>(id:string):T => {const el=document.getElementById(id);if(!el)throw new Error(`Missing ${id}`);return el as T;};
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const text=(s:string)=>esc(s.replaceAll('{host}',hostName()));
let current=Object.hasOwn(views,location.hash.slice(1))?location.hash.slice(1):'runtime', selected=views[current].initial, zoom=1;
const nodeWidth=240,nodeHeight=144,left=22;
let laneWidth=340,boardWidth=0,boardHeight=0;
let positions=new Map<string,{x:number;y:number}>();
let routes:{d:string;lx:number;ly:number}[]=[];
// Reserve a distinct horizontal track for each endpoint and a vertical track for
// each edge in its source lane. Long/return edges never cut through node rows.
function prepareLayout(){
 const view=views[current],rows=[...new Set(view.nodes.map(n=>n.row))].sort((a,b)=>a-b);
 const slots=new Map<string,number>();let rowCount=0;
 for(const row of rows){const groups=view.lanes.map((_,lane)=>view.nodes.filter(n=>n.row===row&&n.lane===lane));const count=Math.max(...groups.map(g=>g.length));groups.forEach(g=>g.forEach((n,i)=>slots.set(n.id,rowCount+i)));rowCount+=count;}
 const nodes=new Map(view.nodes.map(n=>[n.id,n]));
 const bands=Array.from({length:rowCount+1},()=>[] as string[]);
 const laneEdges=view.lanes.map(()=>[] as number[]);
 view.edges.forEach((edge,i)=>{const a=nodes.get(edge.from)!,b=nodes.get(edge.to)!;bands[slots.get(a.id)!+1].push(`s${i}`);bands[slots.get(b.id)!].push(`t${i}`);laneEdges[a.lane].push(i);});
 laneWidth=nodeWidth+left+40+Math.max(...laneEdges.map(es=>es.length))*12;
 const bandTop:number[]=[],rowTop:number[]=[];let y=80;
 for(let row=0;row<=rowCount;row++){bandTop[row]=y;y+=Math.max(54,34+bands[row].length*16);if(row<rowCount){rowTop[row]=y;y+=nodeHeight;}}
 positions=new Map(view.nodes.map(n=>[n.id,{x:n.lane*laneWidth+left,y:rowTop[slots.get(n.id)!]}]));
 boardWidth=view.lanes.length*laneWidth;boardHeight=y+24;
 routes=view.edges.map((edge,i)=>{const a=nodes.get(edge.from)!,b=nodes.get(edge.to)!,p=positions.get(a.id)!,q=positions.get(b.id)!;
  const outgoing=view.edges.filter(e=>e.from===a.id),incoming=view.edges.filter(e=>e.to===b.id);
  const sx=p.x+16+(nodeWidth-96)*(outgoing.indexOf(edge)+1)/(outgoing.length+1),tx=q.x+nodeWidth-64+48*(incoming.indexOf(edge)+1)/(incoming.length+1);
  const sb=slots.get(a.id)!+1,tb=slots.get(b.id)!;
  const sy=bandTop[sb]+24+bands[sb].indexOf(`s${i}`)*16,ty=bandTop[tb]+24+bands[tb].indexOf(`t${i}`)*16;
  const channel=p.x+nodeWidth+22+laneEdges[a.lane].indexOf(i)*12;
  return {d:`M${sx},${p.y+nodeHeight} V${sy} H${channel} V${ty} H${tx} V${q.y-7}`,lx:channel-12,ly:sy};
 });
}
function point(node:NodeData){return positions.get(node.id)!;}
function layout(){$('board').style.width=`${boardWidth}px`;$('board').style.height=`${boardHeight}px`;$('board').style.transform=`scale(${zoom})`;$('scaled').style.width=`${boardWidth*zoom}px`;$('scaled').style.height=`${boardHeight*zoom}px`;$('zoom-value').textContent=`${Math.round(zoom*100)}%`;}
function render(){prepareLayout();const view=views[current];$('view-title').textContent=view.title;$('view-description').textContent=view.description;$('diagram').setAttribute('aria-labelledby',`tab-${current}`);document.querySelectorAll<HTMLButtonElement>('[data-view]').forEach(b=>b.setAttribute('aria-selected',String(b.dataset.view===current)));
const width=boardWidth,height=boardHeight;
let html=view.lanes.map(([name,sub,actor],i)=>`<div class="lane" style="left:${i*laneWidth}px;width:${laneWidth}px;--actor:var(--${actor})"><div class="lane-head"><strong>${text(name)}</strong><span>${text(sub)}</span></div></div>`).join('');
html+=`<svg class="edges" width="${width}" height="${height}" aria-hidden="true"><defs><marker id="arrow" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M0,0 L10,5 L0,10 z" fill="#718e84"/></marker></defs>`;
 view.edges.forEach((edge,i)=>{const p=routes[i];html+=`<g data-route="${i}"><title>${esc(`${i+1}. ${edge.from} → ${edge.to}: ${edge.label||'Continue'}`)}</title><path class="edge-halo" d="${p.d}"/><path class="edge ${edge.type||''}" data-edge="${i}" d="${p.d}" marker-end="url(#arrow)"/><g class="route-number" data-label="${i}"><circle cx="${p.lx}" cy="${p.ly}" r="9"/><text x="${p.lx}" y="${p.ly+3}" text-anchor="middle">${i+1}</text></g></g>`;});html+='</svg>';
html+=view.nodes.map(node=>{const p=point(node);return `<button type="button" class="node ${node.kind||''}" data-node="${node.id}" style="left:${p.x}px;top:${p.y}px;height:${nodeHeight}px;--actor:var(--${node.actor})" aria-pressed="false"><span class="kicker">${node.id} / ${node.actor==='host'?'main model':node.actor==='worker'?'specialist':node.actor}</span><strong>${text(node.title)}</strong><span class="sub">${text(node.sub)}</span></button>`;}).join('');$('board').innerHTML=html;$('print-routes').innerHTML=`<h2>Route key</h2><ol>${view.edges.map(edge=>`<li>${text(view.nodes.find(n=>n.id===edge.from)!.title)} → ${text(view.nodes.find(n=>n.id===edge.to)!.title)}: ${text(edge.label||'Continue')}</li>`).join('')}</ol>`;layout();$('board').querySelectorAll<HTMLButtonElement>('[data-node]').forEach(b=>b.addEventListener('click',()=>select(b.dataset.node!)));select(selected);}
function select(id:string){const view=views[current],node=view.nodes.find(n=>n.id===id);if(!node)return;selected=id;const linked=new Set([id]);view.edges.forEach(edge=>{if(edge.from===id||edge.to===id){linked.add(edge.from);linked.add(edge.to);}});$('board').querySelectorAll<HTMLButtonElement>('[data-node]').forEach(b=>{b.classList.toggle('selected',b.dataset.node===id);b.classList.toggle('dim',!linked.has(b.dataset.node!));b.setAttribute('aria-pressed',String(b.dataset.node===id));});view.edges.forEach((edge,i)=>{const active=edge.from===id||edge.to===id;const path=$('board').querySelector(`[data-edge="${i}"]`)!;path.classList.toggle('active',active);path.classList.toggle('dim',!active);$('board').querySelector(`[data-route="${i}"]`)!.classList.toggle('route-hidden',!active);$('board').querySelector(`[data-label="${i}"]`)!.classList.toggle('dim',!active);});
const next=view.edges.filter(edge=>edge.from===id||edge.to===id).map(edge=>({edge,node:view.nodes.find(n=>n.id===(edge.from===id?edge.to:edge.from))!}));$('inspector').innerHTML=`<span class="owner-tag" style="--actor:var(--${node.actor})">${text(node.actor==='host'?hostName():node.actor==='jev'?'Jev · decision service':node.actor==='worker'?'Specialist agent':node.actor==='runtime'?'Deterministic runtime':'You')}</span><h3>${text(node.title)}</h3><dl><dt>Skill / module</dt><dd>${text(node.skill)}</dd><dt>Receives</dt><dd>${text(node.input)}</dd><dt>What happens</dt><dd><ul>${node.actions.map(a=>`<li>${text(a)}</li>`).join('')}</ul></dd><dt>Returns</dt><dd>${text(node.output)}</dd></dl><div class="connections"><div class="eyebrow" style="margin-top:22px">Connected routes · numbers match the graph</div>${next.length?next.map(({edge,node})=>`<button class="jump" type="button" data-jump="${node.id}"><b>${view.edges.indexOf(edge)+1} · ${edge.from===id?'To':'From'}</b> ${text(node.title)}<br><span>${text(edge.label||'Continue')}</span></button>`).join(''):'<p>Outcome delivered. Run evidence remains archived.</p>'}</div>`;
$('inspector').querySelectorAll<HTMLButtonElement>('[data-jump]').forEach(b=>b.addEventListener('click',()=>{select(b.dataset.jump!);const target=$('board').querySelector<HTMLElement>(`[data-node="${b.dataset.jump}"]`)!;target.scrollIntoView({behavior:'smooth',block:'nearest',inline:'nearest'});}));}
function changeView(key:string){current=key;history.replaceState(null,'',`#${key}`);selected=views[key].initial;zoom=1;render();$('viewport').scrollTo({top:0,left:0,behavior:'instant'});}
function clearHighlight(){$('board').querySelectorAll('.route-hidden').forEach(el=>el.classList.remove('route-hidden'));$('board').querySelectorAll('.dim,.active,.selected').forEach(el=>el.classList.remove('dim','active','selected'));$('board').querySelectorAll('[aria-pressed]').forEach(el=>el.setAttribute('aria-pressed','false'));}
document.querySelectorAll<HTMLButtonElement>('[data-view]').forEach(b=>b.addEventListener('click',()=>changeView(b.dataset.view!)));
$('host').addEventListener('change',render);$('zoom-in').addEventListener('click',()=>{zoom=Math.min(1.3,Math.round((zoom+.1)*10)/10);layout();});$('zoom-out').addEventListener('click',()=>{zoom=Math.max(.6,Math.round((zoom-.1)*10)/10);layout();});$('reset-view').addEventListener('click',()=>{zoom=1;layout();clearHighlight();});
render();
